---
title: "ANES Vote Sup"
author: "James P. Hraba"
date: "1/10/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(here)
library(haven)
library(ggplot2)

#rm(list = ls())

```



```{r}
#loading in data
path <- here("data", "anes_voting_law_data_statePolLean.csv")
anes_voting_law_data_statePolLean <- read.csv(path)

path2 <- here("data", "anes16_with_laws.csv")
anes16_with_laws <- read.csv(path2)

path3 <- here("data", "anes_voting_law_data_with_pol_variables.csv")
anes16_new <- read.csv(path3)

```



```{r}
#combining datasets
anes <- cbind(anes16_new, intent_vote = anes16_with_laws$V161030,
              intent_vote_reg = anes16_with_laws$V161024x)


#renaming variables
anes <- rename(anes, id_law = Check..Photo.ID.vs..No.Photo,
               alt_party = Party.Alignment,
               poverty = Poverty..Over.Under,
               pol_lean = Political.Leaning,
               case_id = V160001...2016.Case.ID,
               state = V161010e...State,
               party_reg = V161019...Party.of.Registration,
               therm_dem = V161086...FT.Dem.Cand,
               therm_rep = V161087...FT.Rep.Cand,
               party_strength = V161156...Strong.Party.Affiliation,
               race = V161310....calc..Race...All,
               income = V161361x...Pre.Income,
               gender = V165723...Gender,
               age = V168254..Age..observed.)

```

```{r}
# 1 = Alternate Party, 0 = Primary Party, NA = Party Not Known
anes$alt_party <- recode(anes$alt_party,
                         'Alternate Party' = 1,
                         'Primary Party' = 0)


# 1 = Democratic, 0 = Republican
anes$pol_lean <- recode(anes$pol_lean, 
                        "Democratic" = 1,
                        "Republican" = 0)


# 1 = Under Poverty Line, 0 = Over Poverty Line
anes$poverty <- recode(anes$poverty,
                       "Under Poverty Line" = 1,
                       "Over Poverty Line" = 0)

# NA = -1: Missing
anes$party_reg <- na_if(anes$party_reg, "-1:Missing")



# 0 = American Indian/Alaskan Native
# 1 = Asian
# 2 = Black/African American
# 3 = Native Hawaiin/Pacific Islander
# 4 = Other Race
# 5 = White
anes$race <- recode(anes$race, 
                    "American Indian/Alaskan Native" = 0,
                   "Asian" = 1,
                    "Black/African American" = 2,
                    "Native Hawaiin/Pacific Islander" = 3,
                    "Other Race" = 4,
                    "White" = 5
                    )


# 1 = 1:Male, 0 = 2:Female
anes$gender <- recode(anes$gender,
                      "1: Male" = 1,
                      "2: Female" = 0)

anes$age <- na_if(anes$age, 
                  "-1:Missing")

anes$id_law <- factor(anes$id_law)

# recoding the DV, Counting R's that are not registered to vote/ does not intend to register as a NO(2) for intent_vote
anes$intent_vote[anes$intent_vote_reg == 1] <-  0

# recoding the DV, Counting R's that registered and voted early as a YES(1) for intent_vote
anes$intent_vote[anes$intent_vote_reg == 4] <-  1 

anes$intent_vote <- recode(anes$intent_vote, "2" = 0)

anes$intent_vote <- na_if(anes$intent_vote, "-8")
anes$intent_vote <- na_if(anes$intent_vote, "-9")
anes_noNA <- na.omit(anes)

```




```{r}
glm_new <- glm(intent_vote ~ id_law + pol_lean + alt_party + poverty,  family = "binomial", data = anes_noNA) 


summary(glm_new)

xtabs(~intent_vote + id_law, data = anes)

ggplot(anes, aes(id_law, intent_vote, color = alt_party)) +
  geom_jitter()
```
for every one unit change in 


